services:
  user-service-1:
    build: ./user-service
    expose:
      - "5000"
    networks:
      - internal

  user-service-2:
    build: ./user-service
    expose:
      - "5000"
    networks:
      - internal

  task-service-1:
    build: ./task-service
    expose:
      - "5000"
    networks:
      - internal
    depends_on:
      - user-service-1

  task-service-2:
    build: ./task-service
    expose:
      - "5000"
    networks:
      - internal
    depends_on:
      - user-service-2

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_ADMIN_PORT}:81"
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm_password"
      DB_MYSQL_NAME: "npm"

    volumes:
      - ./data/nginx-proxy-manager/data:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    depends_on:
      - npm-db
    networks:
      - internal

  npm-db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm_password"
    volumes:
      - ./data/nginx-proxy-manager/mysql:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
